"use client";

import { useMemo, useState } from "react";
import { KK_CALIBRATION_VERSION, KK_REFERENCES, calibrationStatus, evaluateReference } from "../lib/kk-calibration";
import { formatDate, formatPct, formatPrice } from "../lib/display";
import type { AssetId } from "../lib/markets";
import type { SignalSnapshot, Timeframe } from "../lib/regimes";

export default function CalibrationPanel({ asset, timeframe, values }: { asset?: AssetId; timeframe: Timeframe; values: SignalSnapshot["values"] }) {
  const [expanded, setExpanded] = useState(false);
  const evidence = useMemo(() => KK_REFERENCES.filter(reference => reference.asset === asset).map(evaluateReference), [asset]);
  return <details className="calibration-panel" open={expanded} onToggle={event => setExpanded(event.currentTarget.open)}><summary><span><b>KK Supertrend · ATR {values.atrLength} / multiplier {values.factor}</b><small>{calibrationStatus(asset, timeframe)} · {timeframe === "1w" ? "weekly" : "daily"}</small></span><span>{expanded ? "Close" : "Open"} calibration notebook {expanded ? "−" : "+"}</span></summary>
    <div className="calibration-body"><p>Only KK Supertrend uses these screenshot presets. Standard SuperTrend and every other indicator retain their own settings. Registry revision: {KK_CALIBRATION_VERSION}.</p>
      <div className="calibration-controls-guide"><article><h3>ATR length · volatility memory</h3><p>A longer length smooths volatility over more candles and reacts more slowly to new shocks. A shorter length reacts faster. It does not always move the trail in the same direction; that depends on recent volatility.</p></article><article><h3>Multiplier · distance from price</h3><p>A larger multiplier generally puts the trail farther away, causing later and fewer reversals. A smaller multiplier generally brings it closer, causing earlier and more frequent reversals, including more false flips in sideways markets.</p></article></div>
      <p>The calculation uses HL2 ± multiplier × Wilder ATR and a close-confirmed trailing-band recurrence. These are not fixed price offsets. A matching latest level alone does not prove the private chart formula is identical.</p>
      {timeframe === "1d" && !!evidence.length && <p className="readiness-notice">The evidence below is weekly only. It does not validate this daily preset.</p>}
      {!evidence.length && <p>{asset === "btc" ? "BTC retains 10/3 from the original comparison. A numerical reference fixture was not archived, so no fabricated match score is shown." : `No screenshot reference has been recorded for this market/timeframe. ${asset ? "The uncalibrated" : "Equity"} ATR 10 / factor 3 preset is identical to standard SuperTrend 10/3.`}</p>}
      {evidence.map(row => <article className="calibration-reference" key={row.reference.id}><div className="section-heading"><h3>{row.reference.label}</h3><span className={`state-badge ${row.matched ? "bull" : "bear"}`}>{row.matched ? "Reference check passes" : "Reference mismatch"}</span></div><p>Fixture: {row.reference.venue} · {row.reference.asset.toUpperCase()}/{row.reference.denomination} · completed through {formatDate(row.through)}. Screenshot capture time was not recorded.</p>
        <dl><div><dt>Previous → current preset</dt><dd>{row.reference.previous.atrLength}/{row.reference.previous.factor} → {row.preset.atrLength}/{row.preset.factor}</dd></div><div><dt>Screenshot reversal target</dt><dd>{formatPrice(row.reference.target, row.reference.denomination)}</dd></div><div><dt>Calculated on fixed reference history</dt><dd>{formatPrice(row.value, row.reference.denomination)}</dd></div><div><dt>Difference</dt><dd>{formatPrice(row.error, row.reference.denomination)} · {(row.relativeError * 100).toFixed(4)}%</dd></div><div><dt>Previous preset on the same history</dt><dd>{formatPrice(row.previous.values.supertrend, row.reference.denomination)} · {row.previous.state}</dd></div><div><dt>Reference state / reproduced state</dt><dd>{row.reference.state} / {row.current.state}</dd></div><div><dt>Reproduced signal / effective weekly open</dt><dd>{formatDate(row.current.lastFlip)} / {formatDate(row.current.lastFlip == null ? null : row.current.lastFlip + 7 * 86_400_000)}</dd></div><div><dt>ATR as a proportion of price</dt><dd>{formatPct(row.atrRatio)} on this reference</dd></div></dl><p>{row.reference.reason}</p></article>)}
      <h3>Emerging groups, not an automatic rule</h3><p>Weekly presets currently cluster at BTC 10/3; ETH and SOL 10/2; DOGE, LINK, XMR and SUI 15/2. Unit price is not market size, and this small screenshot sample does not establish a market-cap rule. Compare ATR/price and test later screenshots and new assets before generalizing. SOL&apos;s later reference is one check that required no parameter change.</p>
      <p>Reference scores use the archived fixture and its venue, not today&apos;s selected-market candles. Venue, history length, and unfinished candles can explain small differences. Historical backtests are descriptive, not independent proof of a screenshot-fitted preset.</p>
    </div>
  </details>;
}
