"use client";

import { useMemo, useState } from "react";
import { KK_CALIBRATION_VERSION, KK_REFERENCES, calibrationStatus, evaluateReference } from "../lib/kk-calibration";
import { KK_BATCH_EVIDENCE } from "../lib/kk-batch-evidence";
import { KK_FOLLOWUP_EVIDENCE } from "../lib/kk-followup-evidence";
import { KK_SEPTEMBER17_EVIDENCE } from "../lib/kk-september17-evidence";
import { KK_SEPTEMBER21_EVIDENCE } from "../lib/kk-september21-evidence";
import { KK_ARCHIVE_EVIDENCE } from "../lib/kk-archive-evidence";
import { KK_DAILY_EVIDENCE } from "../lib/kk-daily-evidence";
import type { CommodityId } from "../lib/commodities";
import { formatDate, formatPct, formatPrice } from "../lib/display";
import type { AssetId } from "../lib/markets";
import type { StockId } from "../lib/stocks";
import type { SignalSnapshot, Timeframe } from "../lib/regimes";

export default function CalibrationPanel({ asset, stock, commodity, timeframe, values }: { asset?: AssetId; stock?: StockId; commodity?: CommodityId; timeframe: Timeframe; values: SignalSnapshot["values"] }) {
  const [expanded, setExpanded] = useState(false);
  const evidence = useMemo(() => KK_REFERENCES.filter(reference => reference.asset === asset).map(evaluateReference), [asset]);
  const batch = KK_BATCH_EVIDENCE.filter(row => row.asset === (stock ?? asset));
  const daily = timeframe === "1d" ? KK_DAILY_EVIDENCE.find(row => row.asset === (commodity ?? stock ?? asset)) : undefined;
  const archive = KK_ARCHIVE_EVIDENCE.filter(row => !daily && row.asset === (commodity ?? stock ?? asset) && row.timeframe === timeframe);
  const followup = KK_FOLLOWUP_EVIDENCE.filter(row => row.asset === (commodity ?? stock));
  const latest = [...KK_SEPTEMBER21_EVIDENCE.map(row => ({ ...row, reviewedAt: "2026-09-21" })), ...KK_SEPTEMBER17_EVIDENCE.map(row => ({ ...row, reviewedAt: "2026-09-17" }))].filter(row => row.asset === (stock ?? asset));
  return <details className="calibration-panel" open={expanded} onToggle={event => setExpanded(event.currentTarget.open)}><summary><span><b>KK Supertrend · ATR {values.atrLength} / multiplier {values.factor}</b><small>{calibrationStatus(asset, timeframe, stock, commodity)} · {timeframe === "1w" ? "weekly" : "daily"}</small></span><span>{expanded ? "Close" : "Open"} calibration notebook {expanded ? "−" : "+"}</span></summary>
    <div className="calibration-body"><p>Only KK Supertrend uses these screenshot presets. Standard SuperTrend and every other indicator retain their own settings. Registry revision: {KK_CALIBRATION_VERSION}.</p>
      <div className="calibration-controls-guide"><article><h3>ATR length · volatility memory</h3><p>A longer length smooths volatility over more candles and reacts more slowly to new shocks. A shorter length reacts faster. It does not always move the trail in the same direction; that depends on recent volatility.</p></article><article><h3>Multiplier · distance from price</h3><p>A larger multiplier generally puts the trail farther away, causing later and fewer reversals. A smaller multiplier generally brings it closer, causing earlier and more frequent reversals, including more false flips in sideways markets.</p></article></div>
      <p>The calculation uses HL2 ± multiplier × Wilder ATR and a close-confirmed trailing-band recurrence. These are not fixed price offsets. A matching latest level alone does not prove the private chart formula is identical.</p>
      {daily && <article className="calibration-reference"><h3>Daily preset reference · September 22</h3><p>Independent daily families: crypto 15/2–15/5; stocks 15/3, 15/4, 30/2, 30/4; commodities 15/3, 15/4. Weekly settings are unchanged.</p><p>Previous {daily.previous.atrLength}/{daily.previous.factor} → applied {daily.preset.atrLength}/{daily.preset.factor}. September 21 screenshot: {formatPrice(daily.target)}; calculated on archived {daily.source} candles: {formatPrice(daily.value)} ({daily.errorPct.toFixed(2)}%). Screenshot state: {daily.targetState}; calculated: {daily.state}.</p><p>Approximate grouped fit, not a recovered private formula. Larger errors are accepted to keep the preset family small. Venue and history differences remain; daily requires five consecutive confirmations in either direction, with reset on failure. The archived level comparison predates this rule; screenshot counter alignment still needs validation.{daily.pending ? ` This chart showed a pending bullish ${daily.pending}/5 counter.` : ""}</p></article>}
      {archive.map(row => <article className="calibration-reference" key={`${row.timeframe}-${row.filename}`}><h3>September 21 archive · {timeframe === "1w" ? "weekly" : "daily"}</h3><p>{row.filename} · {row.source}. {row.status === "skipped" ? "Skipped: no reliable numeric target." : `Unchanged ATR ${row.atrLength} / multiplier ${row.factor}. Screenshot flip ${row.target}; calculated ${row.value} (${row.errorPct?.toFixed(3)}%). Screenshot state: ${row.targetState}; calculated state: ${row.state}.`}</p><p>{row.status === "daily-unresolved" ? `Screenshot pending count: ${row.pending ?? 0}/5. Five consecutive completed daily confirmations are now required; this reference remains unresolved.` : row.note}</p>{row.status === "daily-unresolved" && <p className="readiness-notice">Reviewed, not validated. The daily charts include separate confirmation/trailing behavior that ATR and multiplier alone do not reliably reproduce. The five-close confirmation rule is implemented; these screenshot levels and counts remain unresolved.</p>}</article>)}
      {timeframe === "1d" && (!!followup.length || !!evidence.length || batch.some(row => row.timeframe === "1w")) && <p className="readiness-notice">The older weekly evidence below does not validate this daily preset.</p>}
      {!!latest.length && timeframe === "1d" && <p className="readiness-notice">The older references below are weekly only; they do not calibrate the daily preset.</p>}
      {!daily && !archive.length && !latest.length && !followup.length && !evidence.length && !batch.length && <p>No screenshot reference has been recorded for this market/timeframe. The uncalibrated ATR 10 / factor 3 preset is identical to standard SuperTrend 10/3.</p>}
      {latest.map(row => <article className="calibration-reference" key={row.filename}><h3>{row.filename} · {row.reviewedAt} check</h3><p>ATR {row.atrLength} / multiplier {row.factor}. Screenshot flip {row.target}; calculated reference {row.value.toFixed(6)} ({row.errorPct.toFixed(4)}%). State: {row.state === "bull" ? "bullish" : "bearish"}.</p><p>{row.source}. Completed weeks through {row.through}; current partial week excluded. {row.note}</p></article>)}
      {followup.map(row => <article className="calibration-reference" key={row.filename}><div className="section-heading"><h3>{row.filename}</h3><span className="state-badge neutral">Approximate feed-specific fit</span></div><p>Weekly screenshot reviewed {row.reviewedAt}; partial current week excluded. Fixed Yahoo reference history: {row.candles} completed weeks, through the week of {formatDate(row.through)}.</p><dl><div><dt>Previous → current weekly preset</dt><dd>{row.previous.atrLength}/{row.previous.factor} → {row.preset.atrLength}/{row.preset.factor}</dd></div><div><dt>Screenshot flip target</dt><dd>{formatPrice(row.target)} · {row.targetState}</dd></div><div><dt>Calculated reference flip</dt><dd>{formatPrice(row.value)} · {row.state}</dd></div><div><dt>Difference</dt><dd>{((row.value / row.target - 1) * 100).toFixed(4)}%</dd></div><div><dt>Previous preset on same history</dt><dd>{formatPrice(row.previousValue)} · {row.previousState}</dd></div></dl><p>{row.note}</p></article>)}
      {batch.map(row => <article className="calibration-reference" key={row.filename}><div className="section-heading"><h3>{row.filename}</h3><span className={`state-badge ${row.ignored ? "neutral" : "bull"}`}>{row.ignored ? "Ignored reference · no preset change" : "Archived reference check passes"}</span></div><p>Captured 8 September 2026 · {row.venue} · {row.timeframe === "1w" ? "weekly" : "daily"}. Full fixed-history checks run in the calibration tests; only their audited results are loaded here.</p><dl><div><dt>Previous → current preset</dt><dd>{row.previous.atrLength}/{row.previous.factor} → {row.preset.atrLength}/{row.preset.factor}</dd></div><div><dt>Screenshot reversal target{row.ignored ? " (ignored)" : ""}</dt><dd>{formatPrice(row.target, row.venue.includes("USDT") ? "USDT" : "USD")}</dd></div><div><dt>Calculated on completed reference candles</dt><dd>{formatPrice(row.value)} · {row.state}</dd></div><div><dt>Difference from target</dt><dd>{row.ignored ? "Not scored: chart ignored" : `${((row.value / row.target - 1) * 100).toFixed(4)}%`}</dd></div><div><dt>Previous preset on the same history</dt><dd>{formatPrice(row.previousValue)} · {row.previousState}</dd></div><div><dt>Last completed reference candle starts</dt><dd>{formatDate(row.through)} · {row.candles} candles</dd></div></dl>{row.note && <p>{row.note}</p>}{row.asset === "hype" && <p>The screenshot uses KuCoin USDT with 91 completed Monday-based weeks. Kraken USD has a shorter history, so its trail need not equal this reference exactly.</p>}</article>)}
      {evidence.map(row => <article className="calibration-reference" key={row.reference.id}><div className="section-heading"><h3>{row.reference.label}</h3><span className={`state-badge ${row.matched ? "bull" : "bear"}`}>{row.matched ? "Reference check passes" : "Reference mismatch"}</span></div><p>Fixture: {row.reference.venue} · {row.reference.asset.toUpperCase()}/{row.reference.denomination} · completed through {formatDate(row.through)}. Screenshot capture time was not recorded.</p>
        <dl><div><dt>Previous → current preset</dt><dd>{row.reference.previous.atrLength}/{row.reference.previous.factor} → {row.preset.atrLength}/{row.preset.factor}</dd></div><div><dt>Screenshot reversal target</dt><dd>{formatPrice(row.reference.target, row.reference.denomination)}</dd></div><div><dt>Calculated on fixed reference history</dt><dd>{formatPrice(row.value, row.reference.denomination)}</dd></div><div><dt>Difference</dt><dd>{formatPrice(row.error, row.reference.denomination)} · {(row.relativeError * 100).toFixed(4)}%</dd></div><div><dt>Previous preset on the same history</dt><dd>{formatPrice(row.previous.values.supertrend, row.reference.denomination)} · {row.previous.state}</dd></div><div><dt>Reference state / reproduced state</dt><dd>{row.reference.state} / {row.current.state}</dd></div><div><dt>Reproduced signal / effective weekly open</dt><dd>{formatDate(row.current.lastFlip)} / {formatDate(row.current.lastFlip == null ? null : row.current.lastFlip + 7 * 86_400_000)}</dd></div><div><dt>ATR as a proportion of price</dt><dd>{formatPct(row.atrRatio)} on this reference</dd></div></dl><p>{row.reference.reason}</p></article>)}
      {stock === "tsla" && <p>Additional reference checked 9 September 2026: TSLA.jpeg, weekly NASDAQ chart, bearish with a bullish flip at $383.88. The existing ATR 15 / factor 2 preset gives $383.8839317 on the fixed completed reference history. No parameter change; the unfinished weekly candle is excluded. Daily TSLA is not calibrated by this weekly image.</p>}
      <h3>Emerging groups, not an automatic rule</h3><p>Weekly presets cluster at BTC 10/3; ETH and SOL 10/2; the other fourteen cryptos and TSLA/NVDA/GOOGL/MU/SNDK/MSTR 15/2. SpaceX weekly remains uncalibrated; its daily 15/4 is an approximate family fit, with five-close confirmation; exact screenshot counter alignment remains unresolved. The stock matches show that 15/2 is not exclusively a small-cap setting. Unit price is not market size, and this sample does not establish a market-cap rule.</p>
      <p>Gold retains 10/2; Silver and Bitmine use the established 15/2 preset family, accepting approximately 4% screenshot-level differences on Yahoo data. These shared presets are not evidence of a large-, mid- or small-cap rule. Additional screenshots on the same feed are needed to validate the fits.</p>
      <p>The September batch matches completed candles much better than partial-candle recalculation. ETH, SOL, LINK, XMR and SUI keep their previous settings; changed flip levels reflect new candles or another venue, not necessarily a new preset.</p>
      <p>Reference scores use the archived fixture and its venue, not today&apos;s selected-market candles. Venue, history length, and unfinished candles can explain small differences. Historical backtests are descriptive, not independent proof of a screenshot-fitted preset.</p>
    </div>
  </details>;
}
