"""Record reviewed calibration decisions; never select by backtest performance."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
candidates=json.loads((HERE/'candidates.json').read_text())
timing={'intc','mrvl','amd','nvda','meta','pltr'}
existing={'sndk','mu','nvda','googl','tsla','spcx'}
notes={
 'crcl-1w':'15/2 matches the bullish regime and September 8 executable flip; the Yahoo level differs by 0.081%.',
 'vvv-1w':'15/2 matches the bullish regime and September 14 executable flip. Coinbase USD is a proxy for CRYPTO:VVVUSD; level error is -0.532%.',
 'bot-1w':'Unresolved: only 20 completed weeks are available. No tested common integer preset reproduces the bullish screenshot regime. Keep the uncalibrated 10/3 fallback; do not substitute the screenshot price for an indicator.',
 'sndk-1w':'Retain 15/2. The level differs by about $0.013; archived Yahoo history begins at the existing February 24, 2025 application cutoff.',
 'intc-1w':'15/2 reproduces 119.42 and the bearish regime through September 14. Including the completed September 21 week flips the model bullish; the screenshot still shows bearish with Bullish 1/1. The private update/confirmation timing is unresolved.',
 'mu-1w':'Retain 15/2; bearish state and displayed reversal level match to the cent.',
 'mrvl-1w':'15/2 reproduces 249.77 and the bearish regime through September 14. The completed September 21 week flips the model bullish; the screenshot still shows bearish with Bullish 1/1. Preserve completed-candle semantics.',
 'amd-1w':'15/2 reproduces 438.38 through September 14 and the historical bullish reversal. The September 21 completed candle raises the model trail to 490.77; do not retune to compensate for the screenshot lag.',
 'nvda-1w':'Retain 15/2: 192.15 matches through September 14. Including September 21 raises the trail to 193.62; bullish state is unchanged.',
 'amzn-1w':'15/2 reproduces the bullish state, 242.65 level, and August 3 executable flip.',
 'meta-1w':'15/2 gives 671.0121 and bearish through September 14, versus screenshot 670.63. Including September 21 flips the model bullish; the image still says bearish and Bullish 1/1. The small prior-level difference and confirmation timing remain disclosed.',
 'googl-1w':'Retain 15/2; the bearish state and 380.37 level match. The screenshot flip date is obscured by candles and was not scored.',
 'tsla-1w':'Retain 15/2; bearish state, 383.88 level, and July 27 executable flip match.',
 'pltr-1w':'15/2 reproduces 141.97 through September 14 and the August 10 executable bullish flip. The completed September 21 candle raises the model trail to 150.36.',
 'spcx-1w':'Unresolved: only 15 complete IPO-era weeks are available. The existing 10/3 gives 211.53 versus 158.13; 15/2 also fails (194.80). No parameter or aggregation change is justified by this short reference.',
 'qnt-1w':'15/2 matches the bullish regime and September 28 executable flip. Coinbase USD is a proxy for CRYPTO:QNTUSD, with +0.488% level difference.',
 'strc-1d':'Apply 30/4: -0.562% level error; July 6 confirmed signal executes July 7, matching the screenshot. A numerically closer 15/5 was rejected because it reverses in August.',
 'crcl-1d':'Apply approximate 50/6: +2.325% level error; September 10 signal executes September 11 as shown. Established stock-family candidates miss the level by at least 26.7%; the closer 10/6 candidate has the wrong reversal date. This extends the daily family and needs more screenshots.',
 'bot-1d':'Unresolved: the default 10/3 remains bearish versus the bullish screenshot. Established daily families also fail; even the nearest bullish common-integer candidate misses the level by over 34%. Keep 10/3 explicitly uncalibrated.',
 'spcx-1d':'Retain approximate 15/4. Level error is +7.525%; the September 14 signal executes September 15, later than the image September 11. Only 73 daily bars are available; this remains a weak fit.',
 'qnt-1d':'Apply approximate 50/4: -2.062% level error, bullish state. Model signal September 12 executes September 13 versus image September 10. The image shows an unfinished September 28 candle and Bearish 1/5; completed-candle replay has no pending count. This is a proxy-feed level/timing compromise, not a confirmation match.',
}
rows=[]
for r in candidates:
 a,tf=r['asset'],r['timeframe'];key=f'{a}-{tf}'
 preset=(10,3) if a in ['bot','spcx'] and tf=='1w' or a=='bot' else (15,2) if tf=='1w' else {'strc':(30,4),'crcl':(50,6),'spcx':(15,4),'qnt':(50,4)}[a]
 c=next(c for c in r['candidates'] if (c['atrLength'],c['factor'])==preset)
 use_previous=tf=='1w' and a in timing
 scored=c['preceding'] if use_previous else c
 previous=(15,2) if tf=='1w' and a in existing and a!='spcx' else (15,4) if a=='spcx' and tf=='1d' else (10,3)
 status='unresolved' if a=='bot' or a=='spcx' and tf=='1w' else 'timing-difference' if use_previous else 'matched' if abs(scored['errorPct'])<.002 else 'approximate'
 d=json.loads((HERE/f'{a}.json').read_text())
 compared=d['weekly'][-2]['time'] if use_previous else None
 from datetime import datetime,timezone
 through=datetime.fromtimestamp(compared/1000,timezone.utc).date().isoformat() if compared else r['through']
 rows.append({k:v for k,v in r.items() if k!='candidates'}|{'reviewedAt':'2026-09-28','previous':{'atrLength':previous[0],'factor':previous[1]},'preset':{'atrLength':preset[0],'factor':preset[1]},'status':status,'value':c['value'],'state':c['state'],'errorPct':c['errorPct'],'lastFlip':c['lastFlip'],'confirmation':c['confirmation'],'comparisonThrough':through,'comparisonValue':scored['value'],'comparisonState':scored['state'],'comparisonErrorPct':scored['errorPct'],'note':notes[key]})
(HERE/'results.json').write_text(json.dumps(rows,indent=2)+'\n')
compact=[{k:v for k,v in r.items() if k not in ['image','imageSha256','bars','pendingCount','pendingDirection','imageLastFlipDate']} for r in rows]
(ROOT/'lib/kk-september28-evidence.ts').write_text('/** Reviewed video references. Current completed-candle and preceding-week comparisons are kept separate. */\nexport const KK_SEPTEMBER28_EVIDENCE = '+json.dumps(compact,indent=2)+' as const;\n')
lines=['# September 28 KK Supertrend calibration and asset additions','', '[Video source](https://www.youtube.com/watch?v=L_CvF4pDmOY&t=2400s). Individual source images remain in `data/kk-research-2026-09-28-video/` and are indexed in the [video inventory](../youtube-2026-09-28-L_CvF4pDmOY/REPORT.md).','', 'Added CRCL, VVV, INTC, MRVL, AMD, AMZN, META, QNT, BOT, STRC, and PLTR. The nine stocks use Yahoo split-adjusted prices; VVV and QNT use Coinbase USD. Stock start dates follow verified provider availability, bounded by the application calendar. STRC is a preferred security, distinct from MSTR.','', 'The 16 weekly references cover six existing stocks and ten additions. STRC has only a daily reference. Five daily references were reviewed: STRC, CRCL, BOT, SPCX, QNT. No hourly chart was used to calibrate a daily model.','', '## Method and limits','', '- Fixed cutoff: September 28, 2026 00:00 UTC. Stocks end September 25; crypto daily ends September 27; the last complete weekly bar starts September 21. Partial candles are excluded.','- Replay the application’s Wilder ATR / HL2 Supertrend calculation and existing five-consecutive-close daily confirmation. The documented [TradingView Supertrend recurrence](https://www.tradingview.com/support/solutions/43000634738-supertrend/) supplies the transparent model; this is not a recovered private MoneyLine formula.','- First check existing compact preset families; retain good existing fits. A bounded diagnostic grid uses ATR lengths 5, 7, 10, 14, 15, 20, 21, 30, 50 and integer multipliers 1–6. Decisions consider the level, regime, and readable historical flip date, never backtest profitability.','- Daily CRCL 50/6 and QNT 50/4 extend the former families. They are approximate, single-video calibrations; CRCL’s executable flip date matches, while QNT’s remains three days later. More same-feed references are needed.','- Six weekly screenshots match the **preceding** completed week substantially better. Report both values; do not drop a completed week in the live engine or shift historical signals to force a match.','- Screenshot flip dates generally describe executable opens, whereas model lastFlip is the signal candle. The report preserves this distinction. GOOGL’s partly obscured date is unscored.','- BOT’s sparse history and SPCX weekly cannot be reproduced reliably by the tested settings. They stay explicitly uncalibrated; no screenshot target is hardcoded into the indicator. STRC weekly has no supplied reference and remains 10/3.','', '## Weekly results','', 'All supported weekly fits use ATR 15 / multiplier 2. BOT and SPCX retain 10/3 as unresolved fallbacks. Error below compares the latest completed-candle model against the screenshot.','', '| Asset | ATR/factor | Screenshot | Latest model | Error | Image/model state | Assessment |','|---|---|---:|---:|---:|---|---|']
for r in rows:
 if r['timeframe']!='1w':continue
 lines.append(f"| {r['asset'].upper()} | {r['preset']['atrLength']}/{r['preset']['factor']} | {r['target']} | {r['value']:.6f} | {r['errorPct']:+.3f}% | {r['targetState']}/{r['state']} | {r['status']} |")
lines+=['','### Preceding-week comparisons','','These comparisons use the September 14 bar as the final completed weekly bar. Live calculations continue through September 21.','','| Asset | Screenshot | September 14 model | Error | Confirmed image/model state |','|---|---:|---:|---:|---|']
for r in rows:
 if r['status']=='timing-difference':lines.append(f"| {r['asset'].upper()} | {r['target']} | {r['comparisonValue']:.6f} | {r['comparisonErrorPct']:+.4f}% | {r['targetState']}/{r['comparisonState']} |")
lines+=['','## Daily results','','| Asset | Previous → applied | Screenshot | Completed model | Error | Image/model state | Assessment |','|---|---|---:|---:|---:|---|---|']
for r in rows:
 if r['timeframe']!='1d':continue
 lines.append(f"| {r['asset'].upper()} | {r['previous']['atrLength']}/{r['previous']['factor']} → {r['preset']['atrLength']}/{r['preset']['factor']} | {r['target']} | {r['value']:.6f} | {r['errorPct']:+.3f}% | {r['targetState']}/{r['state']} | {r['status']} |")
lines+=['','## Per-reference decisions','']
for r in rows:lines.append(f"- **{r['asset'].upper()} {r['timeframe'].upper()}** ([video {r['videoTimestamp']}]({r['videoUrl']})): {r['note']}")
lines+=['','## Persistence and reproducibility','','- `observations.json`: transcribed targets, states, counters, readable dates, video links and source-image hashes.','- `candidates.json`: compact-family and selected additional candidates, with both current and preceding comparisons.','- `*-diagnostics.json`: bounded common-integer scans, including rejected settings.','- Per-asset JSON files: fixed daily and weekly OHLC, quality counts, retrieval timestamps, split signatures, source raw paths and hashes.','- `results.json` and `lib/kk-september28-evidence.ts`: decisions used by the app’s calibration notebook.','- Reproduce with `python3 research/kk-2026-09-28/download.py`, `node --experimental-strip-types scripts/research-kk-september28.ts`, `node --experimental-strip-types scripts/research-kk-september28-diagnostics.ts`, and `python3 research/kk-2026-09-28/register.py`. Downloads require network; fixture replay does not.','- Asset catalogs, selectors, overview routing and the scheduled crypto refresh groups include the additions. The shared stock refresh iterates the stock catalog automatically; the Python research service also includes VVV and QNT.','- No changes to standard SuperTrend, other indicator formulas, completed-bar aggregation, daily confirmation count, or next-open execution.','', '## Validation and deployment','','- Passed 128 unit tests, 15 component tests, and two production-rendered HTML/bundle checks.', '- Passed the production Next.js/Cloudflare Pages build, including TypeScript checking, and ESLint.', '- Passed all six Python research-service tests using isolated temporary pytest/DuckDB dependencies.', '- Replayed all 21 calibration references, checked non-repainting prefixes, partial-candle exclusion, unchanged other indicators, five-close daily confirmation and next-open execution.', '- All 21 source-image files exist and match their archived SHA-256 hashes.', '- All eleven prepared seed files replay idempotently in a temporary SQLite database: thirteen histories with completed-candle counts, actual retrieval timestamps and stock split metadata verified.', '- New VVV/QNT daily and weekly histories were also saved to the local SQLite cache. Recreate seeds with `node --experimental-strip-types scripts/seed-kk-september28.ts`; add `--apply-local` to populate those two local crypto caches.', '- The eleven SQL seed files are in ignored `data/cloudflare-seed/september28-*.sql`; the production Pages bundle is prepared in `dist/cloudflare-pages`.', '- Release follow-up: low-confidence daily fits (STRC, CRCL, QNT, SPCX), unreliable BOT/SPCX fits, weekly timing mismatches and new uncalibrated timeframes have visible KK-specific warnings in both labs and the overview. The assets remain selectable.', '- Hosted deployment uses the reviewed narrow seed files, Pages bundle and refresh Worker; release identifiers are recorded by Cloudflare.','']
(HERE/'REPORT.md').write_text('\n'.join(lines))
print('Registered',len(rows),'references; weekly',sum(r['timeframe']=='1w' for r in rows),'daily',sum(r['timeframe']=='1d' for r in rows))
