import json,hashlib,shutil
from pathlib import Path
P=Path(__file__).resolve().parent
r=json.loads((P/'results.json').read_text());c=json.loads((P/'comparison.json').read_text())
meta={}
archive=Path('data/kk-research-2026-09-22/references');archive.mkdir(parents=True,exist_ok=True)
for a in r:
 src=Path('/home/kos/Downloads')/f'{a}8.png';shutil.copy2(src,archive/src.name)
 meta[a]={'input':str(src),'archivedImage':str(archive/src.name),'sha256':hashlib.sha256(src.read_bytes()).hexdigest(),'snapshotDay':'2026-09-21','download':json.loads((P/f'{a}-raw.json').read_text())['url']}
(P/'provenance.json').write_text(json.dumps(meta,indent=2))
lines=['# KK EMA Ribbon — new daily chart calibration, 22 September 2026','','## Result','','**Retain Close-source EMA 32/34/48/58 for BTC, ETH, SOL and ZEC.** Plot the 32/58 boundaries; use the existing 34/48 alignment checks for the provisional gold/grey/purple state. The new screenshots support the existing shared daily preset. They do not justify coin-specific lengths, a different source, or replacement of the colour rule. No production parameters or deployment were changed.','','## Reference date and feeds','','The latest candle is **21 September 2026**, still incomplete at capture. BTC, ETH and ZEC opening prices match that date on the displayed exchanges. The files were saved on 22 September; that is not the chart candle date. The future crosshair dates in BTC, ETH and ZEC also do not date the last candle.','','SOL has its crosshair on **20 October 2025**: its header OHLC refers to that historical candle. Its latest right-axis price is **116.77**, not the header close 189.82. The chart timeline is consistent with the same 21 September endpoint.','','| Asset | Screenshot market | Comparison feed | Qualification |','|---|---|---|---|','| BTC | Coinbase BTC/USD | Coinbase BTC/USD | Matching venue and quote |','| ETH | Kraken ETH/USD | Kraken ETH/USD | Matching venue and quote |','| SOL | Binance SOL/USD | Binance SOL/USDT | Quote/feed proxy, not exact same-symbol validation |','| ZEC | Binance ZEC/USDT | Binance ZEC/USDT | Matching venue and quote; additional asset evidence |','','Unlike the earlier September 14 screenshots, **these images do not print the ribbon boundary numbers**. Right-axis labels are current market prices, price-axis ticks or cursor levels. The measurements below are raster comparisons, not decimal-exact formula recovery.','','## Existing preset: colour comparison','','The preset was fixed before seeing these images. Coloured/grey pixels near the ribbon classify readable daily observations; obscured or ambiguous observations are omitted. The incomplete 21 September candle is excluded from this historical colour score.','','| Asset | Accepted sample window | Readable samples | Matching samples | Agreement |','|---|---|---:|---:|---:|']
for a,v in r.items():
 d=c['details'][a];n=d['samples'];mis=len(d['mismatches']);lines.append(f"| {a.upper()} | {d['range'][0]} – {d['range'][1]} | {n} | {n-mis} | {100*(n-mis)/n:.1f}% |")
lines+=['','These percentages measure **sampled screenshot-colour agreement**, not trading performance, all-day coverage, or proven exact flip timing. ZEC matched every accepted sample, but omitted/ambiguous pixels and screenshot compression prevent claiming an exact reproduction. Much of BTC/ETH/SOL history overlaps the earlier evidence; this is mainly a closer-view verification, with ZEC adding a new asset.','','The remaining disagreements are between grey and an adjacent trend colour. Several nearby inner-length combinations perform similarly. All four reconstructed screenshot-time states are gold/bullish.','','## Boundary comparison','','The price axes are logarithmic. Label positions establish the log-price mapping. The dated crosshair and latest candle establish the initial time mapping, then candle-wick positions refine it independently of any indicator. Filled regions identify the ribbon, and nearby coloured strokes locate its boundaries. Orange annotations, support/resistance lines and the volume profile are excluded by colour, position and region.','','Median absolute boundary deviations at a standardized 2048-pixel chart width:','','| Asset | Fast EMA32 | Slow EMA58 |','|---|---:|---:|']
for a,v in r.items():lines.append(f"| {a.upper()} | {v['currentGeometry'][0]['medianPx']:.2f} px | {v['currentGeometry'][1]['medianPx']:.2f} px |")
lines+=['','The curves follow the reference closely. Stroke width, antialiasing, candle overlap, chart coordinate registration and SOL feed differences limit precision. Some neighbouring lengths or sources achieve slightly smaller raster errors on individual charts; those rankings are not consistent across assets and do not outweigh the earlier two-asset, four-number rounding matches for Close EMA32/58.','','Calculated values using completed history through 20 September plus the screenshot partial close are below. **These are model outputs, not numbers transcribed from the ribbon.**','','| Asset | EMA32 | EMA58 | Screenshot-time model state |','|---|---:|---:|---|']
for a,d in c['details'].items():lines.append(f"| {a.upper()} | {d['calculatedPartial'][0]:,.4f} | {d['calculatedPartial'][1]:,.4f} | Gold |")
best=c['bestNew'][0]
lines+=['','## Would retuning the grey filter help?', '',f"Scanning ordered inner EMA lengths from 33 to 57 with the 32/58 boundaries fixed favoured {'/'.join(map(str,best['lengths']))} on this batch. Equal-weighted bullish/neutral/bearish agreement, then averaged equally across assets, improves from **{c['current']['newBalanced']*100:.2f}% to {best['newBalanced']*100:.2f}%**.",'',f"However, the same change worsens the archived September 14 batch from **{c['current']['oldBalanced']*100:.2f}% to {best['oldBalanced']*100:.2f}%** by the same metric. The gain on the new batch is small, the inner lengths are not uniquely identified, and the images have measurement uncertainty. **Keep 34/48** rather than selecting a new winner for each batch.",'','The old comparison reuses the archived daily histories and colour observations; the original September 14 files are no longer in Downloads. No claim is made that those old images were re-extracted in this run.','','## Implementation implication','','- Daily source: **Close**.','- EMA lengths: **32, 34, 48, 58**.','- Visible band: **32 / 58** only.','- Gold: EMA32 > EMA34 > EMA48 > EMA58.','- Purple: the reverse ordering.','- Grey: all other orderings, including equality.','- Use the same preset for ZEC; it now has additional approximate daily screenshot support.','- The colour rule remains provisional.','- Weekly settings were not calibrated by these daily charts.','','## Reproducibility and validation','','`download.py` archives the public exchange responses and merges only the same Coinbase market with its local history. Binance supplies 1000 daily bars for SOL/ZEC; Kraken supplies 721 ETH daily bars. `compare.py` checks continuous daily timestamps and valid OHLC ordering. Screenshot partial candles are research-only and never written to production stores.','','Run with NumPy and Pillow: `register.py`, `calibrate.py`, then `compare.py`. `register.py` is independent of previous registration output. `calibrate.py` reads original Downloads images; copies are retained under the ignored local `data/kk-research-2026-09-22/references/` directory. `provenance.json` records image hashes and download URLs. `results.json` and `comparison.json` contain full scores, sample windows and disagreement dates.','','`node --experimental-strip-types research/kk-ema-2026-09-22/verify.ts` confirms that the existing production calculation matches the independent Python EMA values and bullish screenshot-time state for all four assets. This check passed.','']
(P/'REPORT.md').write_text('\n'.join(lines))
print('Wrote REPORT.md and image provenance; archived references locally.')
