/** Generate human-readable evidence, not parameter changes. */
import fs from "node:fs";
import {createHash} from "node:crypto";
const root="research/kk-2026-09-21-archives";
type Candidate={atrLength:number;factor:number;value:number|null;state:string;errorPct:number|null};
type Result={asset:string;source:string;timeframe:string;filename:string;imageSha256:string;target:number|null;state:string;pending?:number;through:string;previous:{atrLength:number;factor:number};candidates:Candidate[]};
const results:Result[]=JSON.parse(fs.readFileSync(`${root}/results.json`,"utf8"));
const fmt=(v:number|null)=>v==null?"—":v<.01?v.toFixed(8):v<10?v.toFixed(6):v.toFixed(2);
const label=(c:{atrLength:number;factor:number})=>`${c.atrLength}/${c.factor}`;
const current=(r:Result)=>r.candidates.find(c=>label(c)===label(r.previous))!;
const closest=(r:Result)=>r.target==null?null:r.candidates.filter(c=>c.state===r.state&&c.errorPct!=null).sort((a,b)=>Math.abs(a.errorPct!)-Math.abs(b.errorPct!))[0]??null;
const notes=(r:Result)=>r.target==null?r.asset==="btc"?"Skipped: current flip clipped; legend is historical under cursor. User permits skipping uncertain charts.":"Skipped: no weekly indicator level is displayed.":r.timeframe==="1d"?r.pending?`Bullish ${r.pending}/5 is pending, not a confirmed bullish regime. Current implementation has no five-bar confirmation counter.`:"Current and closest presets are comparisons, not accepted daily calibrations. A single level cannot establish the different trailing/confirmation rules.":r.asset==="bmnr"?"Approximate fit; Yahoo has much shorter history than the screenshot.":r.asset==="silver"?"Approximate continuous-futures fit; contract/roll differences remain.":r.source==="binance"?"USDT history is a proxy for the chart's USD feed.":["kraken","bitstamp"].includes(r.source)&&!["btc","eth"].includes(r.asset)?"Venue/history-length differences remain; do not transplant this number to another feed.":"Existing preset retained.";
const intro=`# September 21 archives: weekly and daily KK Supertrend\n\nOnly KK Supertrend was investigated. All assets in these archives already exist in the app; the archives contain 16 cryptos, seven stocks, and Gold/Silver futures. AVAX and MSTR are not pictured in these archives. No new assets are required.\n\n25 weekly charts and 25 daily charts were visually read. All screenshots show ordinary candles, not Heikin-Ashi. Weekly BTC is skipped because its current flip is clipped and its legend is showing a historical cursor value. Weekly SpaceX is skipped because no indicator line/value is shown. The remaining 48 values are readable from the right-edge label or unambiguous current-value legend.\n\nThe crypto daily cutoff is September 20 inclusive, stocks/futures September 18 inclusive. September 21 was still in progress when the screenshots were captured (countdowns visible); it is excluded. Weekly comparisons use the completed week starting September 14. Do not insert a screenshot's live candle into a completed-bar backtest.\n\n## Decisions\n\n- **Weekly: retain all existing settings.** The 23 scored charts reproduce the screenshot regimes. Most level differences are small; Bitmine and Silver retain explicitly approximate fits. Gold's existing 10/2 is already within 0.15%, so switching it to 15/2 for a 0.04-percentage-point improvement is not justified.\n- **Daily: reviewed, not reliably calibrated as a group.** The existing four shared presets do not reproduce several readable charts. Pending SUI/OP/Bonk/NVDA/Micron labels reveal a separate five-stage confirmation mechanism; the current implementation has only ATR length and multiplier with immediate completed-close reversal. Even a simple offline five-consecutive-close hypothesis does not recover the chart set. No unverified algorithm is installed.\n- No parameter changes are applied by this report. Closest-preset columns below are research comparisons, not claims of equivalence or recommendations to retune each asset.\n- Standard SuperTrend, all other indicators, execution timing, and production data remain unchanged.\n\n## Weekly results\n\nATR/multiplier; percentage differences are signed, calculated minus screenshot.\n\n| Asset | Preset retained | Image flip | Calculated | Difference | State |\n|---|---|---:|---:|---:|---|\n`;
let report=intro;
for(const r of results.filter(r=>r.timeframe==="1w")){const c=current(r);report+=`| ${r.asset.toUpperCase()} | ${label(r.previous)} | ${fmt(r.target)} | ${r.target==null?"Skipped":fmt(c.value)} | ${r.target==null?"—":c.errorPct!.toFixed(3)+"%"} | ${r.target==null?"Not scored":c.state} |\n`;}
report+="\n## Daily results — current versus closest shared preset\n\n**None of these closest alternatives has been applied.** State agreement is required when ranking. A pending bullish chart is treated as still bearish for this comparison, but the application cannot reproduce its confirmation counter. A close current value is not sufficient to validate the full historical path.\n\n| Asset | Image flip | Current preset | Current flip / state | Current error | Closest same-state preset | Closest flip / error |\n|---|---:|---|---|---:|---|---|\n";
for(const r of results.filter(r=>r.timeframe==="1d")){const c=current(r),b=closest(r);report+=`| ${r.asset.toUpperCase()}${r.pending?` (pending ${r.pending}/5)`:""} | ${fmt(r.target)} | ${label(r.previous)} | ${fmt(c.value)} / ${c.state} | ${c.errorPct!.toFixed(2)}% | ${b?label(b):"None"} | ${b?`${fmt(b.value)} / ${b.errorPct!.toFixed(2)}%`:"No matching regime"} |\n`;}
report+="\n## Interpretation and next step\n\nWeekly evidence continues to support BTC 10/3 (not rescored here), ETH/SOL 10/2, other pictured cryptos and calibrated stocks 15/2, Gold 10/2 and Silver 15/2. This is not proof of a market-cap rule: stocks and cryptos share presets, and the sample is selected rather than representative.\n\nDaily BTC, for example, gets closer under 15/2 (76,868.64 versus 76,922) than 10/3 (74,552.81), but other daily charts cannot be explained by that preset. Arbitrarily selecting a different pair per coin would undermine the shared-pattern objective. The daily set needs the confirmation and trailing-level behavior specified or independently validated across several historical reversals before it can be called calibrated. Useful evidence would include the indicator settings screen or consecutive daily screenshots showing a 1/5 → 5/5 transition, including what happens when a close returns across the threshold.\n\nData-source differences: ETH weekly uses Coinbase, daily uses Bitstamp; XMR weekly Bitfinex, daily Kraken; DOGE weekly Binance USD proxy, daily Coinbase; JUP weekly Kraken, daily Bitstamp; BONK weekly Bitstamp, daily Coinbase; ADA weekly Kraken, daily Coinbase. HYPE and ZEC charts use Coinbase even though app defaults differ. Kraken's REST history is limited; short Bitstamp listings and sparse JUP daily bars constrain reproducibility. Yahoo stock OHLC is split-adjusted. Yahoo futures are continuous series and are not guaranteed to have TradingView's contract-roll treatment.\n\nThe archive script uses paced public requests and reuses one daily fixture per asset/source across both timeframes. No database seeds, refresh jobs or production writes are made. Fixtures are research-only. Backtest regression checks verify next-open execution, annualization, cost sensitivity and rolling-window availability; screenshot-fit data is not independent out-of-sample evidence.\n\n## Image inventory and qualifications\n\n";
for(const r of results)report+=`- ${r.timeframe==="1w"?"Weekly":"Daily"} ${r.asset.toUpperCase()}: **${r.filename}**, ${r.source}. ${notes(r)}\n`;
fs.writeFileSync(`${root}/REPORT.md`,report);
const evidence=results.map(r=>{const c=current(r);return {asset:r.asset,timeframe:r.timeframe,filename:r.filename,imageSha256:r.imageSha256,target:r.target,targetState:r.state,pending:r.pending??null,source:r.source,through:r.through,atrLength:r.previous.atrLength,factor:r.previous.factor,value:r.target==null?null:c.value,state:c.state,errorPct:r.target==null?null:c.errorPct,status:r.target==null?"skipped":r.timeframe==="1w"?"weekly-retained":"daily-unresolved",note:notes(r)};});
fs.writeFileSync("lib/kk-archive-evidence.ts","/** Generated by scripts/report-kk-september21-archives.ts; no preset mutations. */\nexport const KK_ARCHIVE_EVIDENCE = "+JSON.stringify(evidence,null,2)+" as const;\n");
const archives=["2026-09-21 Weekly .zip","2026-09-21 Daily.zip"].map(filename=>({filename,sha256:createHash("sha256").update(fs.readFileSync(`/home/kos/Downloads/${filename}`)).digest("hex")}));
fs.writeFileSync(`${root}/archives.json`,JSON.stringify(archives,null,2)+"\n");
console.log(`Wrote report and ${evidence.length} compact evidence records; no presets changed.`);
